name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install flake8 pytest pylint black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check Black formatting
      run: find . -name "*.py" -exec black {} +

    - name: Lint with Pylint
      run: |
        pylint_output=$(find . -name "*.py" -exec pylint {} + 2>&1)
        pylint_score=$(echo "$pylint_output" | grep -oP "rated at \K([0-9]+\.[0-9]+)")
        echo "$pylint_output"
        if (( $(echo "$pylint_score < 8" | bc -l) )); then
          echo "Pylint score $pylint_score is less than 8. Failing."
          exit 1
        fi

    - name: Run Pytest
      run: pytest

    - name: Sort imports with isort
      run: find . -name "*.py" -exec isort {} +
